version: '3.4'
services:
  web:
    container_name: web
    build: .
    restart: "on-failure"
    environment:
      - NODE_DEV=production
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      gmoney-net:
        aliases:
          - web

networks:
  gmoney-net:
    external: true
