version: '3.4'
services:
  web:
    restart: "on-failure"
    image: 'registry.gitlab.com/roharon/gmoney-store-web'
    container_name: web
    environment:
      - NODE_DEV=production
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    networks:
      gmoney-net:
        aliases:
          - web

networks:
  gmoney-net:
    external: true
