# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Docker CI & CD

on:
  push:
    branches: [ master ]

jobs:
  docker_build_and_push:
    name: Docker Build & Push to registry
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      name: Login to Docker Registry
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_URL }} # default: index.docker.io
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - uses: actions/checkout@v2
    - name: Build the docker
      run: |
        docker network create gmoney-net
        docker-compose -f docker-compose.yml up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check Logs
      run: docker logs web
    - uses: docker/build-push-action@v1
      name: Docker build & Push to Registry
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        repository: ${{ secrets.DOCKER_REGISTRY_USERNAME}}/gmoney-store-web
        tag_with_ref: true
        tag_with_sha: true
