# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Docker CI & CD

on:
  push:
    branches: [ master ]

jobs:
  docker_build_and_push:
    name: Docker Build & Push to registry
    runs-on: ubuntu-latest
    steps:
    - uses: azure/docker-login@v1
      name: Login to Docker Registry
      with:
        login-server: ${{ secrets.DOCKER_REGISTRY_URL }} # default: index.docker.io
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Build the docker
      run: |
        docker network create gmoney-net
        docker-compose up -d
    - name: Check running containers
      run: docker ps -a
    - name: Check Logs
      run: docker logs app
    - uses: docker/build-push-action@v1
      name: Docker build & Push to Registry
      with:
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        registry: ${{ secrets.DOCKER_REGISTRY_URL }}
        repository: ${{ secrets.DOCKER_REGISTRY_USERNAME}}/gmoney-store-server
        tag_with_ref: true
        tag_with_sha: true

  deploy_swarm:
    name: Deploy to Swarm
    needs: docker_build_and_push
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to Docker swarm
      uses: wshihadeh/docker-deployment-action@v1
      with:
        remote_docker_host: ${{ secrets.SERVER_HOSTNAME }}@${{ secrets.SERVER_DOMAIN}}
        ssh_private_key: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SERVER_SSH_PUBLIC_KEY }}
        deployment_mode: docker-swarm
        copy_stack_file: true
        deploy_path: ${{ secrets.SERVER_DEPLOY_PATH }}
        stack_file_name: docker-compose.yml
        keep_files: 5
        args: web